### ISSUE TITLE
[PROJECT] Code Cleanup

### ISSUE THREAD

**Issue by agiveygives** [agiveygives/eso-craft-request#65]
Make improvements to the code base so future development can be done more quickly.

- [ ] issue #11 - Material-UI uplift
- [ ] issue #32 - Cleanup Redux Store
- [ ] issue #30 - Add Documentation
- [ ] issue #34 - Convert to TypeScript
- [ ] issue #29 - Integrate Linter
- [ ] issue #35 - Remove react-shapes dependency
